import './bootstrap';
import { initConfirmForms, initFlashMessages } from './notify';
import { initBlueprint } from './blueprint';
import { initDashboardCalendar } from './dashboard-calendar';
import { initDashboardCharts } from './dashboard-charts';
import { initInlineAttachers } from './inline-attacher';
import { initInvitations } from './invitations';
import { initMemberMenus } from './members';
import { initProjects } from './projects';
import { initSearchablePickers } from './searchable-picker';
import { initSidebar } from './sidebar';
import { initTaskComments } from './task-comments';
import { initTasks } from './tasks';
import { initTheme } from './theme';
import { initTaskRowLiveTimers, initTimeTrackerClock } from './time-tracker';
import { initWorkspaces } from './workspaces';

initTheme();
initFlashMessages();
initConfirmForms();
initSidebar();
initDashboardCharts();
initDashboardCalendar();
initTasks();
initProjects();
initWorkspaces();
initSearchablePickers();
initInlineAttachers();
initInvitations();
initMemberMenus();
initTaskComments();
initTimeTrackerClock();
initTaskRowLiveTimers();
initBlueprint();
